POST http://127.0.0.1:8716/todo HTTP/1.1
content-type: application/json

{
    "todo": "test2"
}

###
GET http://127.0.0.1:8716/todo HTTP/1.1
content-type: application/json

{
}

###
POST  http://127.0.0.1:8716/todo/delete HTTP/1.1
content-type: application/json

{
    "id": "1376220843574562816"
}

###
POST  http://127.0.0.1:8716/todo/finish HTTP/1.1
content-type: application/json

{
    "id": "1376215328933023744",
    "finished": true
}

###
POST  http://127.0.0.1:9527/user/login?redirect=http%3A%2F%2Flocalhost%3A8716%2Ftodo HTTP/1.1
content-type: application/json

{
    "name": "mingor"
}