@base_url=http://127.0.0.1:8716
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhZ2w4cDh4Ymswc2ciLCJleHAiOjE2MTk1MjU5MDV9.2-IusUVLrZqkaZD6jCKLhxNIfkupGb9HwY9hZJMfKlA

###
POST {{base_url}}/todo HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
    "todo": "test"
}

###
GET {{base_url}}/todo HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
}

###
POST  {{base_url}}/todo/delete HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
    "id": "1385897607343116288"
}

###
POST  {{base_url}}/todo/finish HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
    "id": "1385897607343116288",
    "finished": true
}

###
POST  {{base_url}}/todo/edit HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
    "id": "1385897607343116288",
    "Todo": "123"
}

###
POST  {{base_url}}/todo/daily HTTP/1.1
content-type: application/json
Cookie: token={{token}}  

{
    "id": "1385897607343116288",
    "daily": true
}